

function CrimeReport(){
    return(
        <div className="crimereport">
            <h1>Crime Report</h1>
    <table>
      <thead>
        <tr>
          <th>Incident Date</th>
          <th>Incident Time</th>
          <th>Location</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>April 10, 2023</td>
          <td>10:30 PM</td>
          <td>Main Street</td>
          <td>Assault and Battery</td>
        </tr>
        <tr>
          <td>April 11, 2023</td>
          <td>3:45 AM</td>
          <td>Park Avenue</td>
          <td>Burglary</td>
        </tr>
        <tr>
          <td>April 12, 2023</td>
          <td>8:15 PM</td>
          <td>Green Street</td>
          <td>Robbery</td>
        </tr>
        <tr>
          <td>April 13, 2023</td>
          <td>2:00 PM</td>
          <td>Maple Avenue</td>
          <td>Auto Theft</td>
        </tr>
      </tbody>
    </table>
    <div class="footer">
      <p>Generated by XYZ Police Department</p>
    </div>
        </div>
    )
}

export default CrimeReport;